apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: rutcreate/url-shortener
          env:
            - name: DATABASE_URL
              value: mongodb://app-mongo-srv:27017/shorten-url
            - name: RATE_LIMIT_MS
              value: "60"
            - name: BASE_URL
              value: http://localhost:5900

---

apiVersion: v1
kind: Service
metadata:
  name: app-srv
spec:
  type: ClusterIP
  selector:
    app: url-shortener
  ports:
    - name: url-shortener
      protocol: TCP
      port: 3000
      targetPort: 3000
